apiVersion: kyverno.io/v1
kind: ClusterPolicy # Assuming it's a ClusterPolicy
metadata:
  name: disallow-privileged # Ensure this matches the name in your file
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: no-privileged-containers
    match:
      any:
      - resources:
          kinds:
            - Pod
    exclude: # <--- ADD THIS EXCLUDE BLOCK
      any:
      - resources:
          namespaces:
            - falco
    validate:
      message: "Privileged containers are not allowed."
      pattern:
        spec:
          =(ephemeralContainers):
            - =(securityContext):
                =(privileged): "false"
          =(initContainers):
            - =(securityContext):
                =(privileged): "false"
          containers:
            - =(securityContext):
                =(privileged): "false"