apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: required-labels-policy
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: require-app-label
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
            - falco
            - trivy-system
      validate:
        message: "All pods must have the label 'app'."
        pattern:
          metadata:
            labels:
              app: "?*"

    - name: require-environment-label
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
            - falco
            - trivy-system
      validate:
        message: "All pods must have the label 'environment'."
        pattern:
          metadata:
            labels:
              environment: "?*"
